version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgresdb_concursos
    restart: unless-stopped
    environment:
      POSTGRES_DB: concursos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - concursos_network


volumes:
  postgres_data:

networks:
  concursos_network:
    driver: bridge 