"""Constantes do domínio de concursos."""

CONCURSO_STATUS_CHOICES = [
    ("ATIVO", "Ativo"),
    ("INATIVO", "Inativo"),
]

CONCURSO_SITUACAO_INCOMPLETO = "INCOMPLETO"
CONCURSO_SITUACAO_COMPLETO = "COMPLETO"
CONCURSO_SITUACAO_EM_ANDAMENTO = "EM_ANDAMENTO"
CONCURSO_SITUACAO_FINALIZADO = "FINALIZADO"
CONCURSO_SITUACAO_CANCELADO = "CANCELADO"

CONCURSO_SITUACAO_CHOICES = [
    (CONCURSO_SITUACAO_INCOMPLETO, "Incompleto"),
    (CONCURSO_SITUACAO_COMPLETO, "Completo"),
    (CONCURSO_SITUACAO_EM_ANDAMENTO, "Em andamento"),
    (CONCURSO_SITUACAO_FINALIZADO, "Finalizado"),
    (CONCURSO_SITUACAO_CANCELADO, "Cancelado"),
]
