# Generated by Django 5.2.5 on 2025-10-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concursos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Código do Cargo"
            ),
        ),
    ]
