# Generated by Django 5.2.5 on 2026-01-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concursos", "0002_cargo_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="concurso",
            name="codigo",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Código do Concurso"
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="numero_processo",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Número do Processo"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="codigo",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Código do Cargo"
            ),
        ),
    ]
