# Generated by Django 5.2.5 on 2026-01-26 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concursos", "0003_concurso_codigo_concurso_numero_processo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutorizacaoPublicada",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "vagas_sem_efeito",
                    models.BooleanField(default=False, verbose_name="Vagas sem efeito"),
                ),
                (
                    "autorizacoes",
                    models.IntegerField(default=0, verbose_name="Autorizações"),
                ),
                (
                    "autorizacoes_sem_efeito",
                    models.IntegerField(
                        default=0, verbose_name="Autorizações sem efeito"
                    ),
                ),
                (
                    "data_autorizacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da autorização"
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Observação",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autorizacoes",
                        to="concursos.cargo",
                        verbose_name="Cargo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorização Publicada",
                "verbose_name_plural": "Autorizações Publicadas",
                "db_table": "autorizacoes_publicadas",
                "ordering": ["-data_autorizacao", "-criado_em"],
            },
        ),
    ]
