# Generated by Django 5.2.5

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concursos", "0004_autorizacaopublicada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autorizacaopublicada",
            name="vagas_sem_efeito",
        ),
        migrations.RemoveField(
            model_name="autorizacaopublicada",
            name="autorizacoes_sem_efeito",
        ),
    ]
