# Generated by Django 5.2.5 on 2026-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "concursos",
            "0006_concurso_ano_edital_concurso_banca_responsavel_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concurso",
            name="ano_edital",
        ),
        migrations.AddField(
            model_name="concurso",
            name="classificacao_final",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data da Classificação Final",
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="data_abertura",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data de Abertura do Concurso",
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="data_autorizacao",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data de Autorização do Concurso",
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="data_homologacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Homologação"
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="data_prorrogacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Prorrogação"
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="habilitados_geral",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Habilitados (Geral)"
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="habilitados_nna",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Habilitados (NNA)"
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="habilitados_pcd",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Habilitados (PcD)"
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="link_edital",
            field=models.URLField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Link do Edital",
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="retificacoes",
            field=models.TextField(
                blank=True, default="", verbose_name="Retificações"
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("INCOMPLETO", "Incompleto"),
                    ("COMPLETO", "Completo"),
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("FINALIZADO", "Finalizado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="INCOMPLETO",
                max_length=20,
                verbose_name="Situação do Concurso",
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="vigencia_fim",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fim da Vigência"
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="vigencia_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Início da Vigência"
            ),
        ),
    ]
