# Generated by Django 5.2.5 on 2026-07-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concursos", "0005_remove_vagas_sem_efeito_autorizacoes_publicadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="concurso",
            name="ano_edital",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Ano do Edital"
            ),
        ),
        migrations.AddField(
            model_name="concurso",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="concurso",
            name="banca_responsavel",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Banca Responsável"
            ),
        ),
        migrations.AlterField(
            model_name="concurso",
            name="numero_processo",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Número do Processo"
            ),
        ),
    ]
