# Generated by Django 5.2.5 on 2026-07-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concursos", "0006_concurso_ano_edital_concurso_ativo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concurso",
            name="codigo",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Código do Concurso"
            ),
        ),
    ]
